// clients/admincli/src/app/layout/console/console.component.ts
import { Component, OnInit, Input, ViewEncapsulation } from '@angular/core';
import * as neffos from 'neffos.js';
import { environment } from '../../../environments/environment';

@Component({
  selector: 'app-console',
  templateUrl: './console.component.html',
  styleUrls: ['./console.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ConsoleComponent implements OnInit {
  @Input()
  set listening(l: boolean) {
    if (l) {
      this.startListener();
    } else {
      if (this.conn != null && !this.conn.isClosed) {
        this.conn.close();
      }
      this.messages = [
        "Console is sleeping..."
      ];
    }
  }

  conn: neffos.Conn;
  messages: Array<any>;

  constructor() {
  }

  ngOnInit() {
  }

  async startListener() {
    try {
      this.conn = await neffos.dial(`ws://${environment.services.admin}/console`, {
        default: { // "default" namespace.
          _OnNamespaceConnected: (nsConn: neffos.NSConn, msg: neffos.Message) => {
            if (nsConn.conn.wasReconnected()) {
              console.log("re-connected after " + nsConn.conn.reconnectTries.toString() + " trie(s)");
            }
            console.log("connected to namespace: " + msg.Namespace);
          },
          _OnNamespaceDisconnect: (nsConn: neffos.NSConn, msg: neffos.Message) => {
            console.log("disconnected from namespace: " + msg.Namespace);
          },
          console: (nsConn: neffos.NSConn, msg: neffos.Message) => {
            this.messages.push(msg.Body)
          }
        }
      }, { // optional.
          reconnect: 2000,
          // set custom headers.
          headers: {
            // 'X-Username': 'kataras',
          }
        });

      await this.conn.connect("default");
      this.messages = ["Start listening..."];
    } catch (err) {
      console.error(err);
      this.messages = [
        `<i class='red'>Error</i>: ${err}`
      ];
    }
  }
}

// clients/playercli/src/app/game/console.tsx
import * as React from 'react';
import * as neffos from 'neffos.js';
import env from '../services/environment';

interface ConsoleState {
  messages: string[];
}

export class Console extends React.Component<any, ConsoleState> {
  constructor(props: any) {
    super(props);
    this.state = { messages: [] };
  }

  async componentDidMount() {
    try {
      const conn = await neffos.dial(`${env.wsGameSvc}/console`, {
        default: { // "default" namespace.
          _OnNamespaceConnected: (nsConn: neffos.NSConn, msg: neffos.Message) => {
            if (nsConn.conn.wasReconnected()) {
              console.log("re-connected after " + nsConn.conn.reconnectTries.toString() + " trie(s)");
            }
            console.log("connected to namespace: " + msg.Namespace);
          },
          _OnNamespaceDisconnect: (nsConn: neffos.NSConn, msg: neffos.Message) => {
            console.log("disconnected from namespace: " + msg.Namespace);
          },
          console: (nsConn: neffos.NSConn, msg: neffos.Message) => { // "chat" event.
            console.log(msg.Body);
            this.setState({ messages: this.state.messages.concat([msg.Body]) })
          }
        }
      }, { // optional.
          reconnect: 2000,
          // set custom headers.
          headers: {
            // 'X-Username': 'kataras',
          }
        });

      await conn.connect("default");
    } catch (err) {
      console.error(err);
    }
  }

  render() {
    return (
      <ul>
        {this.state.messages.map((msg, index) => <li key={index}>{msg}</li>)}
      </ul>
    );
  }
}
